package org.example.superfoodsservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-10-18T13:50:10.194-05:00
 * Generated source version: 3.1.3
 * 
 */
@WebServiceClient(name = "SuperFoodsService", 
                  wsdlLocation = "file:src/main/resources/SuperFoodsWebService.wsdl",
                  targetNamespace = "http://www.example.org/SuperFoodsService/") 
public class SuperFoodsService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/SuperFoodsService/", "SuperFoodsService");
    public final static QName SuperFoodsServiceSOAP = new QName("http://www.example.org/SuperFoodsService/", "SuperFoodsServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:src/main/resources/SuperFoodsWebService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SuperFoodsService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:src/main/resources/SuperFoodsWebService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SuperFoodsService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SuperFoodsService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SuperFoodsService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SuperFoodsService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SuperFoodsService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SuperFoodsService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SuperFoodsService
     */
    @WebEndpoint(name = "SuperFoodsServiceSOAP")
    public SuperFoodsService getSuperFoodsServiceSOAP() {
        return super.getPort(SuperFoodsServiceSOAP, SuperFoodsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SuperFoodsService
     */
    @WebEndpoint(name = "SuperFoodsServiceSOAP")
    public SuperFoodsService getSuperFoodsServiceSOAP(WebServiceFeature... features) {
        return super.getPort(SuperFoodsServiceSOAP, SuperFoodsService.class, features);
    }

}
